### ISSUE TITLE
mapa mental 

### ISSUE THREAD

**Issue by alexis663** [SistemasTecTlaxiaco/mapa-mental-alexis663#2]
[mapa mental alexis juarez.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-alexis663/files/7290089/mapa.mental.alexis.juarez.pdf)

**Comment by yanet02** [comment]
Manejo conceptual y dominio del tema excelente (25%), Relación entre los conceptos (22%) notable, Calidad de la presentación (22%) notable y la Jerarquía 25% excelente.
Total: 94
Calificación: 18.8%/20%
Calificado por Yanet González García..

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
